name: Literals
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep 'LITERAL_'
        env:
          LITERAL_STRING: ${{ 'Hello, world!' }} # string型
          LITERAL_OMIT_STRING: World # string型(省略記法)
          LITERAL_NUMBER: ${{ 1234 }} # number型
          LITERAL_BOOLEAN: ${{ true }} # boolean型
          LITERAL_NULL: ${{ null }} # null型
